import { mkdir, mkdtemp, rm, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { isBareIdentifier, isWithin, PathEscapeError, readScopedFile } from "./safe-file.js";

describe("isWithin", () => {
  it("accepts the root itself and nested paths", () => {
    expect(isWithin("/a/openspec", "/a/openspec")).toBe(true);
    expect(isWithin("/a/openspec", "/a/openspec/changes/x.md")).toBe(true);
  });

  it("rejects a sibling that only shares a textual prefix", () => {
    expect(isWithin("/a/openspec", "/a/openspec-secrets/x.md")).toBe(false);
  });

  it("rejects a parent path", () => {
    expect(isWithin("/a/openspec", "/a/other.md")).toBe(false);
  });
});

describe("isBareIdentifier", () => {
  it("accepts a plain name", () => {
    expect(isBareIdentifier("safe-file-access")).toBe(true);
    expect(isBareIdentifier("spec.v2")).toBe(true);
  });

  it("rejects a value carrying a path separator", () => {
    // What `/api/specs/..%2F..%2Fpackage.json` decodes to before it reaches a path.
    expect(isBareIdentifier("../../package.json")).toBe(false);
    expect(isBareIdentifier("a/b")).toBe(false);
    expect(isBareIdentifier("a\\b")).toBe(false);
  });

  it("rejects the traversal and current-directory segments", () => {
    expect(isBareIdentifier("..")).toBe(false);
    expect(isBareIdentifier(".")).toBe(false);
  });

  it("rejects an absolute path, an empty value and an embedded NUL", () => {
    expect(isBareIdentifier("/etc/passwd")).toBe(false);
    expect(isBareIdentifier("")).toBe(false);
    expect(isBareIdentifier("spec\0.md")).toBe(false);
  });
});

describe("readScopedFile", () => {
  let root: string;
  let openspecRoot: string;
  /** Outside the project root entirely, so a link into it genuinely escapes. */
  let outsideRoot: string;

  beforeEach(async () => {
    root = await mkdtemp(join(tmpdir(), "safe-file-"));
    openspecRoot = join(root, "openspec");
    await mkdir(join(openspecRoot, "changes"), { recursive: true });
    await writeFile(join(openspecRoot, "changes", "in.md"), "inside", "utf8");
    // An artifact a schema generated outside `openspec/` but inside the project.
    await mkdir(join(root, "adr"), { recursive: true });
    await writeFile(join(root, "adr", "0001-decision.md"), "an adr", "utf8");
    outsideRoot = await mkdtemp(join(tmpdir(), "safe-file-outside-"));
    await writeFile(join(outsideRoot, "secret.md"), "secret", "utf8");
  });

  afterEach(async () => {
    await rm(root, { recursive: true, force: true });
    await rm(outsideRoot, { recursive: true, force: true });
  });

  it("reads a file that resolves inside the project root", async () => {
    const contents = await readScopedFile(root, join(openspecRoot, "changes", "in.md"));
    expect(contents).toBe("inside");
  });

  it("reads a file under the project root but outside `openspec/`", async () => {
    // The case the old `openspec/`-bound boundary refused: an artifact generated by a schema
    // with `generates: "../../../adr/*.md"`.
    const contents = await readScopedFile(root, join(root, "adr", "0001-decision.md"));
    expect(contents).toBe("an adr");
  });

  it("rejects a `..` traversal out of the project root without reading", async () => {
    const escaping = join(root, "openspec", "changes", "..", "..", "..", "elsewhere.md");
    await expect(readScopedFile(root, escaping)).rejects.toBeInstanceOf(PathEscapeError);
  });

  it("rejects a symlink that escapes the project root", async () => {
    const link = join(openspecRoot, "changes", "escape.md");
    await symlink(join(outsideRoot, "secret.md"), link);
    await expect(readScopedFile(root, link)).rejects.toBeInstanceOf(PathEscapeError);
  });

  it("rejects a sibling directory that shares a textual prefix but resolves elsewhere", async () => {
    // `<root>-secrets` textually begins with `<root>`.
    const sibling = `${root}-secrets`;
    await mkdir(sibling, { recursive: true });
    await writeFile(join(sibling, "x.md"), "nope", "utf8");
    await expect(readScopedFile(root, join(sibling, "x.md"))).rejects.toBeInstanceOf(
      PathEscapeError,
    );
    await rm(sibling, { recursive: true, force: true });
  });
});
